import type { FarmRecordsState } from '@/services/farm-records/farm-records.types';

const seedTimestamp = '2026-05-20T08:00:00.000+07:00';

export const demoFarmRecordsState: FarmRecordsState = {
  version: 1,
  farmPlots: [
    {
      id: 'farm-plot-demo-rice-a',
      name: 'Demo Rice Plot A',
      displayCode: 'DEMO-RICE-A',
      areaRai: 8,
      areaNgan: 1,
      areaSquareWah: 20,
      province: 'Pathum Thani',
      district: 'Demo district',
      subdistrict: 'Demo subdistrict',
      coarseLocationLabel: 'Pathum Thani rice-growing area (demo)',
      notes: 'Demo-only plot for local Farm Records foundation. No precise coordinates.',
      isArchived: false,
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
    {
      id: 'farm-plot-demo-mixed-orchard',
      name: 'Demo Mixed Orchard',
      displayCode: 'DEMO-ORCHARD',
      areaRai: 3,
      province: 'Chanthaburi',
      coarseLocationLabel: 'Chanthaburi orchard area (demo)',
      notes: 'Demo-safe orchard example. No farmer name, phone number, or exact location.',
      isArchived: false,
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
  ],
  cropCycles: [
    {
      id: 'crop-cycle-demo-rice-2026-main',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropName: 'Rice',
      variety: 'Jasmine rice demo variety',
      seasonLabel: 'Main season 2026 demo',
      startDate: '2026-05-01',
      expectedHarvestDate: '2026-09-05',
      status: 'active',
      areaRai: 8,
      notes: 'Active demo crop cycle for M83 local-first smoke coverage.',
      createdAt: seedTimestamp,
      updatedAt: seedTimestamp,
    },
  ],
  farmActivityRecords: [
    {
      id: 'activity-demo-rice-planting',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      activityDate: '2026-05-01',
      activityType: 'planting',
      title: 'Broadcast rice seed',
      description: 'Demo planting record for the active rice crop cycle.',
      inputName: 'Rice seed',
      inputQuantity: 160,
      inputUnit: 'kg',
      laborCount: 4,
      laborHours: 6,
      tags: ['demo', 'rice'],
      createdAt: '2026-05-01T17:00:00.000+07:00',
      updatedAt: '2026-05-01T17:00:00.000+07:00',
    },
    {
      id: 'activity-demo-rice-fertilizer',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      activityDate: '2026-05-18',
      activityType: 'fertilizing',
      title: 'First fertilizer application',
      description: 'Demo input record. Not agronomy advice.',
      inputName: 'Demo fertilizer',
      inputQuantity: 8,
      inputUnit: 'bag',
      tags: ['demo', 'input'],
      imageRefs: [
        {
          id: 'image-ref-demo-fertilizer-note',
          localUri: 'local://demo/farm-records/fertilizer-note',
          filename: 'demo-fertilizer-note.jpg',
          caption: 'Metadata placeholder only, no upload in M83.',
          createdAt: '2026-05-18T11:30:00.000+07:00',
        },
      ],
      createdAt: '2026-05-18T11:30:00.000+07:00',
      updatedAt: '2026-05-18T11:30:00.000+07:00',
    },
    {
      id: 'activity-demo-rice-weather-note',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      activityDate: '2026-05-22',
      activityType: 'weather_note',
      title: 'Rain after field work',
      weatherSummary: 'Moderate rain in the area, recorded as coarse text only.',
      tags: ['demo', 'weather'],
      createdAt: '2026-05-22T18:00:00.000+07:00',
      updatedAt: '2026-05-22T18:00:00.000+07:00',
    },
    {
      id: 'activity-demo-orchard-labor',
      farmPlotId: 'farm-plot-demo-mixed-orchard',
      activityDate: '2026-05-12',
      activityType: 'labor',
      title: 'Clean orchard rows',
      laborCount: 2,
      laborHours: 5,
      tags: ['demo', 'orchard'],
      createdAt: '2026-05-12T16:00:00.000+07:00',
      updatedAt: '2026-05-12T16:00:00.000+07:00',
    },
  ],
  farmFinanceEntries: [
    {
      id: 'finance-demo-rice-seed',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      relatedActivityRecordId: 'activity-demo-rice-planting',
      entryDate: '2026-05-01',
      direction: 'expense',
      category: 'seed',
      title: 'Rice seed purchase',
      amount: 3500,
      currency: 'THB',
      quantity: 160,
      unit: 'kg',
      buyerOrVendor: 'Demo agriculture shop',
      paymentMethod: 'cash',
      note: 'Demo-safe expense. No real vendor identity.',
      createdAt: '2026-05-01T18:00:00.000+07:00',
      updatedAt: '2026-05-01T18:00:00.000+07:00',
    },
    {
      id: 'finance-demo-rice-fertilizer',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      relatedActivityRecordId: 'activity-demo-rice-fertilizer',
      entryDate: '2026-05-18',
      direction: 'expense',
      category: 'fertilizer',
      title: 'Demo fertilizer bags',
      amount: 5200,
      currency: 'THB',
      quantity: 8,
      unit: 'bag',
      buyerOrVendor: 'Demo input supplier',
      paymentMethod: 'cash',
      receiptImageRefs: [
        {
          id: 'receipt-ref-demo-fertilizer',
          localUri: 'local://demo/farm-finance/fertilizer-receipt',
          filename: 'demo-fertilizer-receipt.jpg',
          caption: 'Receipt metadata placeholder only.',
          createdAt: '2026-05-18T12:00:00.000+07:00',
        },
      ],
      createdAt: '2026-05-18T12:00:00.000+07:00',
      updatedAt: '2026-05-18T12:00:00.000+07:00',
    },
    {
      id: 'finance-demo-rice-labor',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      relatedActivityRecordId: 'activity-demo-rice-planting',
      entryDate: '2026-05-01',
      direction: 'expense',
      category: 'labor',
      title: 'Planting labor',
      amount: 2400,
      currency: 'THB',
      quantity: 4,
      unit: 'person',
      paymentMethod: 'cash',
      createdAt: '2026-05-01T18:10:00.000+07:00',
      updatedAt: '2026-05-01T18:10:00.000+07:00',
    },
    {
      id: 'finance-demo-rice-machinery',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      entryDate: '2026-05-03',
      direction: 'expense',
      category: 'machinery',
      title: 'Field preparation machine rental',
      amount: 1800,
      currency: 'THB',
      buyerOrVendor: 'Demo machine service',
      paymentMethod: 'cash',
      createdAt: '2026-05-03T15:00:00.000+07:00',
      updatedAt: '2026-05-03T15:00:00.000+07:00',
    },
    {
      id: 'finance-demo-orchard-income',
      farmPlotId: 'farm-plot-demo-mixed-orchard',
      entryDate: '2026-05-15',
      direction: 'income',
      category: 'crop_sale',
      title: 'Mixed fruit sale demo',
      amount: 35000,
      currency: 'THB',
      quantity: 700,
      unit: 'kg_yield',
      buyerOrVendor: 'Demo local buyer',
      paymentMethod: 'bank_transfer',
      note: 'Demo income record for ledger summary.',
      createdAt: '2026-05-15T14:00:00.000+07:00',
      updatedAt: '2026-05-15T14:00:00.000+07:00',
    },
  ],
  farmHarvestRecords: [
    {
      id: 'harvest-demo-rice-first-cut',
      farmPlotId: 'farm-plot-demo-rice-a',
      cropCycleId: 'crop-cycle-demo-rice-2026-main',
      harvestDate: '2026-09-02',
      cropName: 'Rice',
      quantity: 3.2,
      quantityUnit: 'ton',
      normalizedQuantityKg: 3200,
      grade: 'Demo standard paddy',
      buyer: 'Demo local mill',
      salePricePerKg: 10.9,
      grossIncome: 34880,
      note: 'Demo harvest quantity for local cost-per-kg readiness. No real buyer identity.',
      createdAt: '2026-09-02T16:00:00.000+07:00',
      updatedAt: '2026-09-02T16:00:00.000+07:00',
    },
  ],
  migrations: ['m83-demo-seed-v1'],
  updatedAt: seedTimestamp,
};

export function createDemoFarmRecordsState(): FarmRecordsState {
  return {
    ...demoFarmRecordsState,
    farmPlots: demoFarmRecordsState.farmPlots.map((plot) => ({ ...plot })),
    cropCycles: demoFarmRecordsState.cropCycles.map((cycle) => ({ ...cycle })),
    farmActivityRecords: demoFarmRecordsState.farmActivityRecords.map((record) => ({
      ...record,
      imageRefs: record.imageRefs?.map((imageRef) => ({ ...imageRef })),
      tags: record.tags ? [...record.tags] : undefined,
    })),
    farmFinanceEntries: demoFarmRecordsState.farmFinanceEntries.map((entry) => ({
      ...entry,
      receiptImageRefs: entry.receiptImageRefs?.map((imageRef) => ({ ...imageRef })),
    })),
    farmHarvestRecords: demoFarmRecordsState.farmHarvestRecords.map((record) => ({ ...record })),
    migrations: [...demoFarmRecordsState.migrations],
  };
}
