import type {
  NextPhaseOption,
  NextPhaseOptionId,
  PhaseDecisionPlan,
  PhaseDependency,
  PhaseExecutionTrack,
  PhaseRiskRegisterItem,
} from '@/services/phase-planning/phase-decision.types';

const sharedSupabasePrerequisites: PhaseDependency[] = [
  {
    id: 'staging-project',
    label: 'Supabase staging project',
    detail: 'สร้าง project staging แยกจาก production และใช้ anon key เท่านั้นใน frontend',
    status: 'partial',
    route: '/app/supabase-readiness',
  },
  {
    id: 'sql-rls-manual',
    label: 'SQL/RLS manual execution',
    detail: 'ต้องรัน schema SQL และ RLS policy SQL ใน staging ด้วยคนก่อนทดสอบข้อมูลจริง',
    status: 'partial',
    route: '/app/supabase-sql-checklist',
  },
  {
    id: 'service-role-boundary',
    label: 'Service-role boundary',
    detail: 'service-role key ต้องอยู่เฉพาะ backend/Edge Function secret store ไม่อยู่ใน Vite หรือ browser',
    status: 'ready',
    route: '/app/supabase-connection',
  },
];

export const nextPhaseOptionLabels: Record<NextPhaseOptionId, string> = {
  real_supabase_staging: 'Supabase staging + SQL/RLS',
  real_phone_auth_staging: 'Phone Auth staging',
  real_guest_sync_staging: 'Guest Sync staging',
  real_ai_text_proxy: 'AI text proxy',
  real_plant_vision_proxy: 'Plant vision proxy',
  pwa_offline_mobile_shell: 'PWA/mobile shell',
  closed_test_preparation: 'Closed test preparation',
};

const options: NextPhaseOption[] = [
  {
    id: 'real_supabase_staging',
    rank: 1,
    title: 'เริ่ม Supabase staging connection + SQL/RLS execution',
    shortLabel: nextPhaseOptionLabels.real_supabase_staging,
    summary:
      'เป็นทางที่ปลอดภัยที่สุดสำหรับเปลี่ยนจาก prototype ไปสู่ backend จริง เพราะพิสูจน์ schema, RLS, env, และ rollback ก่อน auth หรือ cloud sync',
    recommendedWhen: 'เลือกเมื่อเป้าหมายคือทำฐานข้อมูล staging ให้เชื่อถือได้ก่อนเพิ่มฟีเจอร์จริง',
    readinessScore: { score: 78, label: 'พร้อมเริ่มแบบ manual staging', blockerCount: 0, warningCount: 5 },
    riskLevel: 'medium',
    benefits: [
      'ยืนยันว่า schema/RLS draft ใช้งานได้บน staging จริง',
      'ลดความเสี่ยงก่อน phone auth, guest sync, และ admin actions',
      'สร้าง Cloudflare preview env plan โดยไม่แตะ production secrets',
    ],
    risks: [
      'รัน SQL ผิด project อาจกระทบข้อมูลจริงถ้าไม่ตรวจ staging',
      'RLS ที่ยังไม่ทดสอบกับ user จริงอาจเปิดข้อมูลกว้างเกินไป',
      'การตั้ง env ผิดอาจทำให้ app ดูเหมือนเชื่อม production',
    ],
    blockers: ['ยังห้ามใช้ service-role key ใน frontend', 'ต้องรัน SQL/RLS แบบ manual และ verify ก่อนเปิด flag จริง'],
    prerequisites: sharedSupabasePrerequisites,
    recommendedBranch: 'staging/supabase',
    primaryRoute: '/app/supabase-readiness',
  },
  {
    id: 'real_phone_auth_staging',
    rank: 2,
    title: 'เปิด phone OTP เฉพาะ staging หลัง Supabase พร้อม',
    shortLabel: nextPhaseOptionLabels.real_phone_auth_staging,
    summary: 'ทดสอบ Supabase Auth phone OTP, redirect URL, session persistence, และ rollback โดยยังไม่เปิด production login',
    recommendedWhen: 'เลือกหลัง SQL/RLS staging ผ่าน และพร้อมรับค่า SMS/provider cost ในวงจำกัด',
    readinessScore: { score: 65, label: 'พร้อมวางแผน แต่ยังไม่ควรเปิดจริง', blockerCount: 2, warningCount: 6 },
    riskLevel: 'high',
    benefits: [
      'สร้าง session ownership จริงสำหรับข้อมูลผู้ใช้',
      'เป็น prerequisite ของ cloud sync และ user-owned writes',
      'ช่วยตรวจ UX สมัครภายหลังสำหรับเกษตรกร',
    ],
    risks: ['มีค่า SMS และ abuse risk', 'redirect URL ผิดทำให้ login หลุด', 'session ownership ผิดอาจโยงข้อมูลผิดคน'],
    blockers: ['ต้องมี staging Supabase env พร้อม', 'ต้องมี SMS provider/rate-limit policy ที่ชัดเจน'],
    prerequisites: [
      ...sharedSupabasePrerequisites,
      {
        id: 'phone-auth-plan',
        label: 'Phone OTP staging plan',
        detail: 'ตรวจ redirect URL, test phone numbers, rate limit, logout, และ rollback ก่อนส่ง OTP จริง',
        status: 'partial',
        route: '/app/auth/phone-staging',
      },
    ],
    recommendedBranch: 'staging/supabase',
    primaryRoute: '/app/auth/phone-staging',
  },
  {
    id: 'real_guest_sync_staging',
    rank: 3,
    title: 'ทดสอบ Guest Sync Edge Function หลังมี session จริง',
    shortLabel: nextPhaseOptionLabels.real_guest_sync_staging,
    summary: 'พิสูจน์ idempotency, consent, merge rules, audit log, และ rollback ก่อนเปิด cloud sync ให้ผู้ใช้',
    recommendedWhen: 'เลือกเมื่อ phone auth staging มี authenticated user และ RLS owner checks ผ่านแล้ว',
    readinessScore: { score: 58, label: 'contract พร้อม แต่ต้องมี auth ก่อน', blockerCount: 3, warningCount: 6 },
    riskLevel: 'high',
    benefits: ['ย้าย Guest Memory ไป cloud ได้อย่างมีเจ้าของข้อมูล', 'ลด duplicate rows ด้วย idempotency key', 'เตรียม backup/restore story'],
    risks: ['merge ผิดอาจทำให้ข้อมูลซ้ำหรือหาย', 'partial success ต้องมี audit/rollback', 'ต้องกัน service-role key ให้อยู่หลังบ้านเท่านั้น'],
    blockers: ['ยังไม่มี real Supabase Auth session', 'ยังไม่ได้ deploy Edge Function', 'ยังไม่เปิด cloud sync'],
    prerequisites: [
      {
        id: 'real-session-owner',
        label: 'Real session ownership',
        detail: 'ต้องรู้ user_id จาก Supabase Auth ก่อน sync ข้อมูลใด ๆ ไป cloud',
        status: 'blocked',
        route: '/app/auth/status',
      },
      {
        id: 'edge-contract',
        label: 'Guest Sync Edge contract',
        detail: 'M29 เตรียม contract แล้ว แต่ยังไม่ deploy และยังไม่ call endpoint จริง',
        status: 'partial',
        route: '/app/guest-sync-edge',
      },
    ],
    recommendedBranch: 'staging/supabase',
    primaryRoute: '/app/guest-sync-edge',
  },
  {
    id: 'real_ai_text_proxy',
    rank: 4,
    title: 'สร้าง AI text proxy staging หลัง backend boundary ชัด',
    shortLabel: nextPhaseOptionLabels.real_ai_text_proxy,
    summary: 'เพิ่ม backend-owned AI text proxy พร้อม provider-key protection, credit enforcement, cost caps, และ safety logs',
    recommendedWhen: 'เลือกเร็วขึ้นได้ถ้าต้องการ demo value ของ AI ก่อน full Supabase path',
    readinessScore: { score: 62, label: 'พร้อมทดลองเป็น branch แยก', blockerCount: 2, warningCount: 7 },
    riskLevel: 'high',
    benefits: ['เพิ่มคุณค่าหลักของ product ได้เร็ว', 'พิสูจน์ cost/latency/safety ก่อน vision', 'ไม่ต้องรอ plant image upload เต็มรูปแบบ'],
    risks: ['provider key ต้องไม่อยู่ใน frontend', 'AI อาจให้คำแนะนำเสี่ยงถ้าไม่มี safety layer', 'ค่าใช้จ่ายเกิดได้ทันทีเมื่อเปิด provider'],
    blockers: ['ต้องมี backend proxy จริงก่อน call provider', 'ต้องมี rate limit และ safety logging'],
    prerequisites: [
      {
        id: 'ai-proxy-contract',
        label: 'AI proxy adapter status',
        detail: 'ใช้ contract/adapter ที่มีอยู่ แต่เปลี่ยน provider call ให้เกิดหลัง backend เท่านั้น',
        status: 'partial',
        route: '/app/ai-proxy-status',
      },
      {
        id: 'cost-guard',
        label: 'Cost guardrails',
        detail: 'กำหนด daily quota, timeout, abuse controls, และ fallback message ก่อนเปิดจริง',
        status: 'missing',
        route: '/app/ai-credits',
      },
    ],
    recommendedBranch: 'staging/ai-proxy',
    primaryRoute: '/app/ai-proxy-status',
  },
  {
    id: 'real_plant_vision_proxy',
    rank: 5,
    title: 'Plant vision proxy หลัง text proxy และ upload/storage พร้อม',
    shortLabel: nextPhaseOptionLabels.real_plant_vision_proxy,
    summary: 'เชื่อม AI vision แบบ backend-owned พร้อม image compression, storage TTL, consent, safety disclaimer, และ expert escalation',
    recommendedWhen: 'เลือกหลัง text proxy ผ่าน cost/safety และมี storage/upload staging ที่ตรวจแล้ว',
    readinessScore: { score: 44, label: 'ยังต้องมี backend/storage ก่อน', blockerCount: 5, warningCount: 8 },
    riskLevel: 'critical',
    benefits: ['เป็นฟีเจอร์หลักสำหรับวิเคราะห์โรคพืชจริง', 'ใช้ M31 compression เพื่อลดต้นทุน vision', 'สร้างข้อมูล plant analysis history จริงได้ในอนาคต'],
    risks: ['รูปภาพมี privacy risk สูง', 'คำตอบโรคพืชอาจทำให้เกิดความเสียหายถ้าไม่ใส่ guardrail', 'ต้นทุน vision สูงกว่า text'],
    blockers: ['ยังไม่มี upload/storage bucket จริง', 'ยังไม่มี vision backend proxy', 'ยังไม่มี expert review/escalation workflow'],
    prerequisites: [
      {
        id: 'image-preflight',
        label: 'Image compression/preflight',
        detail: 'M31 พร้อมเป็น local-only foundation แต่ยังไม่มี upload จริง',
        status: 'ready',
        route: '/app/image-preflight',
      },
      {
        id: 'ai-text-proxy',
        label: 'Text proxy and safety baseline',
        detail: 'ควรพิสูจน์ text proxy, credit, cost, และ safety logs ก่อน vision',
        status: 'missing',
        route: '/app/ai-proxy-status',
      },
    ],
    recommendedBranch: 'staging/ai-proxy',
    primaryRoute: '/app/analyze',
  },
  {
    id: 'pwa_offline_mobile_shell',
    rank: 6,
    title: 'เตรียม PWA/offline/mobile shell หลัง backend เสถียร',
    shortLabel: nextPhaseOptionLabels.pwa_offline_mobile_shell,
    summary: 'ทำ app shell, offline UX, install prompt, และ mobile packaging โดยยังแยกจาก backend experiments',
    recommendedWhen: 'เลือกเมื่อ core flows เสถียรหรือเมื่อต้องการ field test แบบมือถือก่อน production',
    readinessScore: { score: 55, label: 'วางแผนได้ แต่ยังไม่ควรล็อกก่อน backend path', blockerCount: 2, warningCount: 5 },
    riskLevel: 'medium',
    benefits: ['ช่วยทดสอบกับเกษตรกรในมือถือจริง', 'เตรียม offline-first UX', 'ลด friction ก่อน closed test'],
    risks: ['offline cache ผิดอาจแสดงข้อมูลเก่าโดยไม่เตือน', 'push/install UX ต้องมี consent ชัด', 'mobile wrapper อาจซ่อนปัญหา backend readiness'],
    blockers: ['ยังไม่มี production privacy/security review', 'ยังไม่มี final routing/offline cache policy'],
    prerequisites: [
      {
        id: 'prototype-stable',
        label: 'Stable prototype on main',
        detail: 'ต้อง tag snapshot และคง main เป็น stable prototype ก่อนแยก mobile branch',
        status: 'partial',
        route: '/app/mvp-snapshot',
      },
    ],
    recommendedBranch: 'staging/mobile',
    primaryRoute: '/app/mvp-snapshot',
  },
  {
    id: 'closed_test_preparation',
    rank: 7,
    title: 'Closed test preparation หลังมี boundary และ rollback',
    shortLabel: nextPhaseOptionLabels.closed_test_preparation,
    summary: 'เตรียม tester list, privacy copy, feedback loop, route checklist, and rollback plan สำหรับทดสอบวงจำกัด',
    recommendedWhen: 'เลือกหลัง staging path แรกผ่านและทีมพร้อมรับ feedback จากผู้ใช้จริง',
    readinessScore: { score: 50, label: 'เริ่ม checklist ได้ แต่ยังไม่พร้อมเปิดทดสอบ', blockerCount: 4, warningCount: 5 },
    riskLevel: 'high',
    benefits: ['ได้ feedback จริงจากเกษตรกร', 'เจอ UX/ภาษา/มือถือก่อน production', 'ช่วยตัดสินใจฟีเจอร์ถัดไปจากข้อมูลจริง'],
    risks: ['ผู้ใช้เข้าใจผิดว่าเป็น production app', 'ข้อมูล mock อาจถูกตีความเป็นข้อมูลจริง', 'ยังไม่มี support/incident workflow'],
    blockers: ['ต้องมี privacy notice และ consent', 'ต้องมี rollback/support owner', 'ต้องไม่มี production claims บนหน้าจอ'],
    prerequisites: [
      {
        id: 'route-checklist',
        label: 'Route checklist',
        detail: 'ต้องตรวจ core, auth, Supabase, AI, My Farm, community, admin ก่อนและหลังงาน backend',
        status: 'partial',
        route: '/app/qa',
      },
    ],
    recommendedBranch: 'main',
    primaryRoute: '/app/qa',
  },
];

const executionTracks: PhaseExecutionTrack[] = [
  {
    id: 'main-stable',
    branchName: 'main',
    label: 'Stable prototype',
    purpose: 'เก็บ M01-M36 prototype ที่ build ผ่านและไม่มี real backend/API behavior เป็น baseline',
    allowedChanges: ['bug fix เล็กที่ไม่เพิ่ม integration จริง', 'docs/report updates', 'route checklist fixes'],
    forbiddenChanges: ['real secrets', 'service-role key', 'provider API calls', 'backend writes', 'auth enablement'],
    mergeRules: ['merge staging กลับ main เฉพาะเมื่อ lint/build/manual route checks ผ่าน', 'ต้องคง local/mock fallback เมื่อไม่มี .env.local'],
    rollbackRules: ['tag snapshot ก่อน merge ใหญ่', 'ถ้า staging ทำให้ route หลักพัง ให้ revert merge commit ไม่แตะ user data'],
    testCommands: ['npm run lint', 'npm run build'],
    previewStrategy: 'Cloudflare production-like preview เฉพาะ mock/local จนกว่า staging branch ผ่าน security review',
  },
  {
    id: 'staging-supabase',
    branchName: 'staging/supabase',
    label: 'Supabase/Auth/Guest Sync experiments',
    purpose: 'ทดลอง staging project, SQL/RLS, phone auth, session ownership, and Guest Sync Edge Function แบบแยกจาก main',
    allowedChanges: ['Supabase anon env wiring', 'manual SQL/RLS verification', 'phone auth staging only', 'Edge Function contract implementation'],
    forbiddenChanges: ['production project URL', 'service-role key in frontend', 'cloud sync default on', 'writes without owner/session checks'],
    mergeRules: ['ต้องมี staging-only env matrix', 'RLS tests with anon/authenticated owner/other user ผ่าน', 'manual rollback plan checked'],
    rollbackRules: ['ปิด feature flags ก่อน revert code', 'เก็บ SQL rollback/manual cleanup checklist', 'ลบ staging env vars ถ้าสงสัย leak'],
    testCommands: ['npm run lint', 'npm run build', 'manual route checks for /app/supabase-readiness and /app/auth/status'],
    previewStrategy: 'Cloudflare preview branch with staging anon key only; no service-role or production secrets',
  },
  {
    id: 'staging-ai-proxy',
    branchName: 'staging/ai-proxy',
    label: 'AI proxy experiments',
    purpose: 'ทดลอง text proxy และต่อยอด vision proxy หลังมี cost/safety/rate-limit guards',
    allowedChanges: ['backend-owned provider calls', 'credit enforcement', 'safety logging', 'fixture fallback'],
    forbiddenChanges: ['provider key in frontend', 'vision upload before storage/consent ready', 'AI answer without agriculture safety copy'],
    mergeRules: ['ต้องมี cost cap, timeout, abuse guard, fallback behavior, and safety test prompts', 'ต้องไม่ทำให้ local fixture mode พัง'],
    rollbackRules: ['ปิด AI backend flag', 'rotate provider key ถ้าสงสัย leak', 'restore fixture-only mode immediately'],
    testCommands: ['npm run lint', 'npm run build', 'manual route checks for /app/ai and /app/ai-proxy-status'],
    previewStrategy: 'Cloudflare preview with backend secret store only; no provider key in Vite env',
  },
  {
    id: 'staging-mobile',
    branchName: 'staging/mobile',
    label: 'PWA/mobile shell experiments',
    purpose: 'ทดลอง app shell, offline UX, install flow, and closed-test packaging หลัง prototype เสถียร',
    allowedChanges: ['PWA manifest draft', 'offline shell planning', 'mobile viewport polish', 'closed-test route checklist'],
    forbiddenChanges: ['push permission prompt without consent plan', 'cache real sensitive data', 'hide local/mock notices'],
    mergeRules: ['mobile route checks pass', 'offline copy clearly marks stale/demo data', 'no production store claim'],
    rollbackRules: ['disable service worker/PWA registration flag', 'clear preview cache guidance', 'return to web-only shell'],
    testCommands: ['npm run lint', 'npm run build', 'manual mobile route checks'],
    previewStrategy: 'Preview deployment for device testing only; no App Store/Play Store production submission yet',
  },
];

const riskRegister: PhaseRiskRegisterItem[] = [
  {
    id: 'secrets-in-frontend',
    title: 'Secret leaked into frontend',
    level: 'critical',
    owner: 'owner/admin',
    mitigation: 'ใช้ anon key เท่านั้นใน Vite/Cloudflare public env และเก็บ service-role/provider keys ใน backend secret store',
    stopCondition: 'หยุดทันทีถ้าพบ service-role-like key, provider key, หรือ production secret ใน repo/frontend env',
  },
  {
    id: 'rls-gap',
    title: 'RLS allows cross-user access',
    level: 'critical',
    owner: 'backend',
    mitigation: 'ทดสอบ anon, owner, other authenticated user, moderator/admin และ service-role job context บน staging',
    stopCondition: 'หยุดถ้า user A อ่าน/เขียนข้อมูล user B ได้โดยไม่ได้ตั้งใจ',
  },
  {
    id: 'ai-cost-safety',
    title: 'AI cost or unsafe advice',
    level: 'high',
    owner: 'ai/backend',
    mitigation: 'เริ่ม text proxy ด้วย quota, timeout, logging, safety prompt, and fallback ก่อนเปิด vision',
    stopCondition: 'หยุดถ้าไม่มี cost cap หรือคำตอบ AI ไม่มีคำเตือนเกษตรปลอดภัย',
  },
  {
    id: 'mock-data-confusion',
    title: 'Users mistake mock data for production',
    level: 'high',
    owner: 'product',
    mitigation: 'คงป้าย demo/local/mock และห้าม production claims ใน route สำคัญ',
    stopCondition: 'หยุด closed test ถ้าผู้ทดสอบเข้าใจว่าราคา/อากาศ/ผลวิเคราะห์เป็นข้อมูลจริง',
  },
  {
    id: 'branch-drift',
    title: 'Staging branches drift from stable main',
    level: 'medium',
    owner: 'engineering',
    mitigation: 'rebase/merge main ตามรอบสั้น, tag snapshots, and verify route checklist before merge',
    stopCondition: 'หยุด merge ถ้า staging ทำให้ M01-M35 routes พังหรือ app ต้องมี .env.local เพื่อเปิด',
  },
];

export function runPhaseDecisionPlan(): PhaseDecisionPlan {
  return {
    generatedAt: '2026-05-23T00:00:00+07:00',
    milestone: 'M36',
    overallReadiness: {
      score: 64,
      label: 'Prototype พร้อมเข้าสู่ staging แบบควบคุม แต่ยังไม่พร้อม production',
      blockerCount: 7,
      warningCount: 14,
    },
    recommendation: {
      recommendedOptionId: 'real_supabase_staging',
      title: 'แนะนำให้เริ่มจาก Supabase staging + SQL/RLS execution',
      summary:
        'ลำดับนี้ลดความเสี่ยงที่สุด เพราะยืนยันฐานข้อมูล, RLS, env, และ rollback ก่อนเปิด auth, cloud sync, AI, หรือ mobile wrapper จริง',
      recommendedOrder: [
        'real_supabase_staging',
        'real_phone_auth_staging',
        'real_guest_sync_staging',
        'real_ai_text_proxy',
        'real_plant_vision_proxy',
        'pwa_offline_mobile_shell',
      ],
      rationale: [
        'Supabase/RLS เป็นฐานความปลอดภัยของ user-owned data และ admin/backend workflows',
        'Phone auth ต้องตามหลัง schema/RLS เพื่อพิสูจน์ session ownership',
        'Guest sync ต้องตามหลัง auth เพราะ sync ต้องผูกข้อมูลกับเจ้าของจริง',
        'AI text proxy เพิ่มคุณค่าได้เร็ว แต่ต้องมี backend-owned secrets และ cost guard',
        'Plant vision ควรมาหลัง text proxy เพราะมี privacy/cost/safety risk สูงกว่า',
        'PWA/mobile shell ควรทำหลัง route และ backend boundary เสถียรพอสำหรับ field test',
      ],
      acceleratorNote: 'ถ้าเป้าหมายคือ demo value ให้ทีม/นักลงทุนก่อน AI text proxy สามารถทำเร็วกว่านี้ได้ แต่ต้องอยู่ใน staging/ai-proxy พร้อม cost/safety guardrails',
      guardrails: [
        'ยังไม่เปิดระบบจริงในหน้านี้',
        'ห้ามใส่ service-role key หรือ provider key ใน frontend',
        'main ต้องยังเป็น stable prototype และ app ต้องเปิดได้โดยไม่มี .env.local',
      ],
    },
    options,
    executionTracks,
    riskRegister,
    productionBlockers: [
      'ยังไม่มี real Supabase staging SQL/RLS verification',
      'ยังไม่มี real Supabase Auth session ownership',
      'ยังไม่มี Guest Sync Edge Function deployment หรือ backend-owned sync',
      'ยังไม่มี backend-owned AI proxy, provider-key storage, cost cap, or safety log',
      'ยังไม่มี production privacy/security review, monitoring, rate limits, backups, or incident plan',
      'mock/demo data ใน weather, prices, content, community, notifications, and admin ยังไม่ใช่ production data',
    ],
    safeNextSteps: [
      'tag หรือเก็บ snapshot ของ main หลัง M36 build ผ่าน',
      'สร้าง branch staging/supabase จาก main เพื่อทดลอง Supabase เท่านั้น',
      'ใส่ Supabase URL/anon key เฉพาะ local/Cloudflare preview env ไม่ commit ลง repo',
      'รัน SQL/RLS บน staging ด้วยคนตามคู่มือ แล้วตรวจ route checklist ก่อนเปิด auth',
      'คง feature flags real auth/cloud sync/AI/backend เป็น false จนกว่าจะผ่าน staging checks',
    ],
  };
}
