import type {
  CropCalculatorKey,
  CropCalculatorProfile,
} from '@/services/agri-calculators/crop-calculator-profile.types';

const planningOnlyNote = 'ตัวอย่างนี้เป็นค่าเริ่มต้นเพื่อช่วยกรอก ไม่ใช่คำแนะนำทางวิชาการสุดท้าย';
const fertilizerPlanningNote =
  'ใช้ช่วยวางแผนจากค่าที่ผู้ใช้กรอกเอง ยังไม่ใช่อัตราแนะนำตามชนิดพืช ดิน หรือฤดู';

export const cropCalculatorProfiles: CropCalculatorProfile[] = [
  {
    cropKey: 'rice',
    thaiDisplayName: 'ข้าว',
    shortLabel: 'ข้าว',
    commonSpacingExamples: [
      {
        id: 'rice-transplant-25x25',
        label: 'นาดำตัวอย่าง 25 x 25 ซม.',
        rowSpacingCm: 25,
        plantSpacingCm: 25,
        usableAreaPercent: 85,
        seedlingBufferPercent: 10,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'rice-5rai', label: 'แปลงตัวอย่าง 5 ไร่', areaValue: 5, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'rice-panicle-sample',
        label: 'ตัวอย่างชั่งผลผลิตจาก 20 จุด',
        landSizeValue: 5,
        landSizeUnit: 'rai',
        sampleCount: 20,
        averageWeightKg: 0.18,
        estimatedTotalUnits: 15000,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'rice-cost-scaffold',
      label: 'โครงต้นทุนข้าว 5 ไร่',
      landSizeValue: 5,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าไถ/เตรียมดิน', 'ค่าเมล็ดพันธุ์', 'ค่าปุ๋ย', 'ค่าน้ำ/สูบน้ำ', 'ค่าเก็บเกี่ยว'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ต้องตรวจชนิดดิน อายุข้าว และคำแนะนำเจ้าหน้าที่ก่อนวางแผนปุ๋ย', 'ไม่แนะนำสารเคมีหรืออัตราใช้ยา'],
  },
  {
    cropKey: 'cassava',
    thaiDisplayName: 'มันสำปะหลัง',
    shortLabel: 'มัน',
    commonSpacingExamples: [
      {
        id: 'cassava-100x80',
        label: 'มันสำปะหลัง 100 x 80 ซม.',
        rowSpacingCm: 100,
        plantSpacingCm: 80,
        usableAreaPercent: 90,
        seedlingBufferPercent: 8,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'cassava-10rai', label: 'แปลงตัวอย่าง 10 ไร่', areaValue: 10, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'cassava-root-sample',
        label: 'ตัวอย่างชั่งหัวจาก 10 กอ',
        landSizeValue: 10,
        landSizeUnit: 'rai',
        sampleCount: 10,
        averageWeightKg: 3,
        estimatedTotalUnits: 18000,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'cassava-cost-scaffold',
      label: 'โครงต้นทุนมัน 10 ไร่',
      landSizeValue: 10,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าท่อนพันธุ์', 'ค่าเตรียมดิน', 'ค่าปลูก', 'ค่ากำจัดวัชพืช', 'ค่าขุด/ขนส่ง'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['พื้นที่ ดิน และพันธุ์มีผลต่อการวางแผนมาก', 'ไม่แนะนำสารกำจัดวัชพืชหรือผลิตภัณฑ์ใด'],
  },
  {
    cropKey: 'sugarcane',
    thaiDisplayName: 'อ้อย',
    shortLabel: 'อ้อย',
    commonSpacingExamples: [
      {
        id: 'sugarcane-row-150',
        label: 'อ้อยแถว 150 ซม. ตัวอย่าง',
        rowSpacingCm: 150,
        plantSpacingCm: 50,
        usableAreaPercent: 88,
        seedlingBufferPercent: 6,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'sugarcane-20rai', label: 'แปลงตัวอย่าง 20 ไร่', areaValue: 20, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'sugarcane-stalk-sample',
        label: 'ตัวอย่างชั่งลำอ้อย',
        landSizeValue: 20,
        landSizeUnit: 'rai',
        sampleCount: 15,
        averageWeightKg: 1.2,
        estimatedTotalUnits: 160000,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'sugarcane-cost-scaffold',
      label: 'โครงต้นทุนอ้อย 20 ไร่',
      landSizeValue: 20,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าพันธุ์อ้อย', 'ค่าเตรียมดิน', 'ค่าเครื่องจักร', 'ค่าตัด/ขน', 'ค่าบำรุงตอ'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ต้องแยกอ้อยปลูกใหม่กับอ้อยตอในอนาคต', 'ไม่แนะนำสารเคมีหรืออัตราปุ๋ยเฉพาะไร่'],
  },
  {
    cropKey: 'maize',
    thaiDisplayName: 'ข้าวโพด',
    shortLabel: 'ข้าวโพด',
    commonSpacingExamples: [
      {
        id: 'maize-75x25',
        label: 'ข้าวโพด 75 x 25 ซม.',
        rowSpacingCm: 75,
        plantSpacingCm: 25,
        usableAreaPercent: 90,
        seedlingBufferPercent: 8,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'maize-5rai', label: 'แปลงตัวอย่าง 5 ไร่', areaValue: 5, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'maize-ear-sample',
        label: 'ตัวอย่างชั่งฝัก/ต้น',
        landSizeValue: 5,
        landSizeUnit: 'rai',
        sampleCount: 20,
        averageWeightKg: 0.25,
        estimatedTotalUnits: 32000,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'maize-cost-scaffold',
      label: 'โครงต้นทุนข้าวโพด 5 ไร่',
      landSizeValue: 5,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าเมล็ดพันธุ์', 'ค่าเตรียมดิน', 'ค่าปุ๋ย', 'ค่าแรงดูแล', 'ค่าเก็บเกี่ยว/สี'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ต้องระบุชนิดข้าวโพดและฤดูปลูกก่อนคำแนะนำใด ๆ', 'ไม่แนะนำสารกำจัดศัตรูพืช'],
  },
  {
    cropKey: 'eucalyptus',
    thaiDisplayName: 'ยูคาลิปตัส / ยูคา',
    shortLabel: 'ยูคา',
    commonSpacingExamples: [
      {
        id: 'eucalyptus-300x200',
        label: 'ยูคา 3 x 2 ม. ตัวอย่าง',
        rowSpacingCm: 300,
        plantSpacingCm: 200,
        usableAreaPercent: 88,
        seedlingBufferPercent: 5,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'eucalyptus-10rai', label: 'สวนตัวอย่าง 10 ไร่', areaValue: 10, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'eucalyptus-tree-sample',
        label: 'ตัวอย่างน้ำหนักต่อหน่วยที่กรอกเอง',
        landSizeValue: 10,
        landSizeUnit: 'rai',
        sampleCount: 20,
        averageWeightKg: 1,
        estimatedTotalUnits: 2600,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'eucalyptus-cost-scaffold',
      label: 'โครงต้นทุนยูคา 10 ไร่',
      landSizeValue: 10,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าต้นพันธุ์', 'ค่าเตรียมดิน', 'ค่าปลูก', 'ค่าดูแลสวน', 'ค่าตัด/ขนส่ง'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ระยะปลูกจริงขึ้นกับพันธุ์ พื้นที่ และเป้าหมายการตัด', 'ไม่แนะนำสารเคมีหรืออัตราปุ๋ยเฉพาะแปลง'],
  },
  {
    cropKey: 'chili',
    thaiDisplayName: 'พริก',
    shortLabel: 'พริก',
    commonSpacingExamples: [
      {
        id: 'chili-80x50',
        label: 'พริก 80 x 50 ซม. ตัวอย่าง',
        rowSpacingCm: 80,
        plantSpacingCm: 50,
        usableAreaPercent: 78,
        seedlingBufferPercent: 12,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'chili-2ngan', label: 'แปลงตัวอย่าง 2 งาน', areaValue: 2, areaUnit: 'ngan', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'chili-plant-sample',
        label: 'ตัวอย่างชั่งผลผลิตพริกต่อต้น',
        landSizeValue: 2,
        landSizeUnit: 'ngan',
        sampleCount: 20,
        averageWeightKg: 0.08,
        estimatedTotalUnits: 1200,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'chili-cost-scaffold',
      label: 'โครงต้นทุนพริก 2 งาน',
      landSizeValue: 2,
      landSizeUnit: 'ngan',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าต้นกล้า/เมล็ด', 'ค่าวัสดุปลูก', 'ค่าปุ๋ย', 'ค่าน้ำ', 'ค่าแรงเก็บ/คัด'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['พริกมีรอบเก็บเกี่ยวและโรคแมลงแตกต่างกันมากตามพื้นที่', 'ไม่แนะนำสารกำจัดศัตรูพืชหรืออัตราใช้ยา'],
  },
  {
    cropKey: 'oil_palm',
    thaiDisplayName: 'ปาล์มน้ำมัน',
    shortLabel: 'ปาล์ม',
    commonSpacingExamples: [
      {
        id: 'oil-palm-900x900',
        label: 'ปาล์มน้ำมัน 9 x 9 ม. ตัวอย่าง',
        rowSpacingCm: 900,
        plantSpacingCm: 900,
        usableAreaPercent: 84,
        seedlingBufferPercent: 4,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'oil-palm-10rai', label: 'สวนตัวอย่าง 10 ไร่', areaValue: 10, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'oil-palm-bunch-sample',
        label: 'ตัวอย่างชั่งทะลายปาล์ม',
        landSizeValue: 10,
        landSizeUnit: 'rai',
        sampleCount: 12,
        averageWeightKg: 18,
        estimatedTotalUnits: 220,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'oil-palm-cost-scaffold',
      label: 'โครงต้นทุนปาล์ม 10 ไร่',
      landSizeValue: 10,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าต้นพันธุ์', 'ค่าดูแลสวน', 'ค่าปุ๋ย', 'ค่าเก็บเกี่ยว', 'ค่าขนส่ง'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ต้องแยกอายุปาล์ม สภาพดิน และผลผลิตจริงก่อนวางแผน', 'ไม่แนะนำอัตราปุ๋ยเฉพาะสวนหรือสารเคมีใด'],
  },
  {
    cropKey: 'durian',
    thaiDisplayName: 'ทุเรียน',
    shortLabel: 'ทุเรียน',
    commonSpacingExamples: [
      {
        id: 'durian-800x800',
        label: 'ทุเรียน 8 x 8 ม. ตัวอย่าง',
        rowSpacingCm: 800,
        plantSpacingCm: 800,
        usableAreaPercent: 82,
        seedlingBufferPercent: 5,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'durian-3rai', label: 'สวนตัวอย่าง 3 ไร่', areaValue: 3, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'durian-fruit-sample',
        label: 'ตัวอย่างน้ำหนักผลทุเรียน',
        landSizeValue: 3,
        landSizeUnit: 'rai',
        sampleCount: 10,
        averageWeightKg: 3,
        estimatedTotalUnits: 450,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'durian-cost-scaffold',
      label: 'โครงต้นทุนสวนทุเรียน 3 ไร่',
      landSizeValue: 3,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าต้นพันธุ์/ดูแลต้น', 'ค่าระบบน้ำ', 'ค่าปุ๋ย/อินทรียวัตถุ', 'ค่าแรงตัดแต่ง', 'ค่าเก็บเกี่ยว'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ทุเรียนต้องแยกอายุต้น ระยะออกดอก และผลผลิตจริงก่อนวางแผน', 'ไม่แนะนำฮอร์โมน สารเคมี หรือผลิตภัณฑ์ใด'],
  },
  {
    cropKey: 'longan',
    thaiDisplayName: 'ลำไย',
    shortLabel: 'ลำไย',
    commonSpacingExamples: [
      {
        id: 'longan-600x600',
        label: 'ลำไย 6 x 6 ม. ตัวอย่าง',
        rowSpacingCm: 600,
        plantSpacingCm: 600,
        usableAreaPercent: 82,
        seedlingBufferPercent: 5,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'longan-5rai', label: 'สวนตัวอย่าง 5 ไร่', areaValue: 5, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'longan-tree-sample',
        label: 'ตัวอย่างชั่งผลต่อต้น',
        landSizeValue: 5,
        landSizeUnit: 'rai',
        sampleCount: 8,
        averageWeightKg: 40,
        estimatedTotalUnits: 220,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'longan-cost-scaffold',
      label: 'โครงต้นทุนสวนลำไย 5 ไร่',
      landSizeValue: 5,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าตัดแต่งกิ่ง', 'ค่าระบบน้ำ', 'ค่าปุ๋ย', 'ค่าแรงเก็บเกี่ยว', 'ค่าคัด/ขนส่ง'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ต้องแยกระยะพักต้น ออกดอก และติดผลก่อนคำแนะนำใด ๆ', 'ไม่แนะนำสารบังคับดอกหรือสารเคมี'],
  },
  {
    cropKey: 'rubber',
    thaiDisplayName: 'ยางพารา',
    shortLabel: 'ยาง',
    commonSpacingExamples: [
      {
        id: 'rubber-700x300',
        label: 'ยางพารา 7 x 3 ม. ตัวอย่าง',
        rowSpacingCm: 700,
        plantSpacingCm: 300,
        usableAreaPercent: 86,
        seedlingBufferPercent: 5,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'rubber-10rai', label: 'สวนตัวอย่าง 10 ไร่', areaValue: 10, areaUnit: 'rai', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'rubber-tree-sample',
        label: 'ตัวอย่างน้ำยางต่อต้น',
        landSizeValue: 10,
        landSizeUnit: 'rai',
        sampleCount: 20,
        averageWeightKg: 0.35,
        estimatedTotalUnits: 760,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'rubber-cost-scaffold',
      label: 'โครงต้นทุนสวนยาง 10 ไร่',
      landSizeValue: 10,
      landSizeUnit: 'rai',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าต้นพันธุ์', 'ค่าดูแลสวน', 'ค่าปุ๋ย', 'ค่าแรงกรีด', 'ค่าอุปกรณ์เก็บน้ำยาง'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ต้องแยกยางอ่อน ยางเปิดกรีด และสภาพดินก่อนวางแผน', 'ไม่แนะนำสารเคมีหรือผลิตภัณฑ์ใด'],
  },
  {
    cropKey: 'vegetable_mixed',
    thaiDisplayName: 'ผักผสม',
    shortLabel: 'ผัก',
    commonSpacingExamples: [
      {
        id: 'vegetable-50x40',
        label: 'ผักแปลง 50 x 40 ซม.',
        rowSpacingCm: 50,
        plantSpacingCm: 40,
        usableAreaPercent: 75,
        seedlingBufferPercent: 15,
        note: planningOnlyNote,
      },
    ],
    commonUnitExamples: [
      { id: 'vegetable-2ngan', label: 'แปลงตัวอย่าง 2 งาน', areaValue: 2, areaUnit: 'ngan', note: planningOnlyNote },
    ],
    yieldEstimateInputExamples: [
      {
        id: 'vegetable-bunch-sample',
        label: 'ตัวอย่างชั่งผักเป็นหน่วย',
        landSizeValue: 2,
        landSizeUnit: 'ngan',
        sampleCount: 20,
        averageWeightKg: 0.25,
        estimatedTotalUnits: 1800,
        note: planningOnlyNote,
      },
    ],
    costInputExample: {
      id: 'vegetable-cost-scaffold',
      label: 'โครงต้นทุนผัก 2 งาน',
      landSizeValue: 2,
      landSizeUnit: 'ngan',
      fertilizerCost: 0,
      laborCost: 0,
      waterCost: 0,
      machineryCost: 0,
      otherCost: 0,
      expectedYieldKg: 0,
      note: 'เติมพื้นที่และหมวดต้นทุนก่อน ผู้ใช้ต้องกรอกจำนวนเงินจริงเอง',
    },
    costCategoriesCommonlyUsed: ['ค่าเมล็ด/ต้นกล้า', 'ค่าวัสดุปลูก', 'ค่าปุ๋ย', 'ค่าน้ำ', 'ค่าแรงเก็บ/คัด'],
    fertilizerPlanningStatus: 'planning_only',
    fertilizerPlanningNote,
    safetyDisclaimerNotes: ['ผักหลายชนิดมีระยะปลูกและอายุเก็บเกี่ยวต่างกันมาก', 'ไม่แนะนำสารกำจัดศัตรูพืชหรืออัตราใช้ยา'],
  },
];

export const cropCalculatorProfileOptions = cropCalculatorProfiles.map((profile) => ({
  value: profile.cropKey,
  label: profile.thaiDisplayName,
}));

export function getCropCalculatorProfile(cropKey: CropCalculatorKey) {
  return cropCalculatorProfiles.find((profile) => profile.cropKey === cropKey) ?? cropCalculatorProfiles[0];
}

export function isCropCalculatorKey(value: unknown): value is CropCalculatorKey {
  return typeof value === 'string' && cropCalculatorProfiles.some((profile) => profile.cropKey === value);
}
