import type { ManualCommodityPriceRow, ManualFertilizerPriceRow } from '@/services/prices/price.types';

export const ownerManualPriceCommodityTargets = [
  { code: 'rice', nameTh: 'ข้าว' },
  { code: 'rubber', nameTh: 'ยางพารา' },
  { code: 'cassava', nameTh: 'มันสำปะหลัง' },
  { code: 'sugarcane', nameTh: 'อ้อย' },
] as const;

// Owner-provided real rows belong here only after source, unit, updatedAt, fetchedAt,
// and original source context are verified. It intentionally stays empty until then
// so sample prices never become live prices by accident.
export const manualCommodityPriceRows: ManualCommodityPriceRow[] = [
  {
    category: 'crop',
    commodityCode: 'rice',
    commodityNameTh: 'ข้าวเปลือกหอมมะลิ',
    currency: 'THB',
    fetchedAt: '2026-05-27T18:20:00+07:00',
    id: 'moc-r11055-rice-jasmine-paddy-2026-05-27',
    marketName: 'ราคาขายส่งข้าว ผลิตภัณฑ์ข้าวและกระสอบป่าน',
    notes: 'MOC product_id R11055; แสดงช่วง price_min-price_max ของวันที่สำรวจ 2026-05-27',
    price: 16200,
    priceMax: 18600,
    showOnHome: true,
    sourceAttribution: 'ข้อมูลราคาสินค้าเกษตร กรมการค้าภายใน กระทรวงพาณิชย์',
    sourceDisplayName: 'กรมการค้าภายใน กระทรวงพาณิชย์',
    sourceName: 'MOC Open Data / กรมการค้าภายใน',
    sourceType: 'api',
    sourceUrl: 'https://dataapi.moc.go.th/gis-product-prices?product_id=R11055&from_date=2026-05-01&to_date=2026-05-27',
    trend: 'unknown',
    unit: 'บาท/ตัน',
    updatedAt: '2026-05-27T00:00:00+07:00',
  },
  {
    category: 'rubber',
    commodityCode: 'rubber',
    commodityNameTh: 'ยางแผ่นดิบชั้น 3',
    currency: 'THB',
    fetchedAt: '2026-05-27T18:20:00+07:00',
    id: 'moc-w16023-rubber-sheet-surat-thani-2026-05-27',
    marketName: 'ราคาเกษตรกรขายได้',
    notes: 'MOC product_id W16023; ยางแผ่นดิบชั้น 3 ราคาเกษตรกรขายได้ จ.สุราษฎร์ธานี',
    price: 79,
    province: 'สุราษฎร์ธานี',
    showOnHome: true,
    sourceAttribution: 'ข้อมูลราคาสินค้าเกษตร กรมการค้าภายใน กระทรวงพาณิชย์',
    sourceDisplayName: 'กรมการค้าภายใน กระทรวงพาณิชย์',
    sourceName: 'MOC Open Data / กรมการค้าภายใน',
    sourceType: 'api',
    sourceUrl: 'https://dataapi.moc.go.th/gis-product-prices?product_id=W16023&from_date=2026-05-01&to_date=2026-05-27',
    trend: 'unknown',
    unit: 'บาท/ กก.',
    updatedAt: '2026-05-27T00:00:00+07:00',
  },
  {
    category: 'crop',
    commodityCode: 'cassava',
    commodityNameTh: 'มันสำปะหลัง',
    currency: 'THB',
    fetchedAt: '2026-05-27T18:20:00+07:00',
    id: 'moc-w16031-cassava-nakhon-ratchasima-2026-05-27',
    marketName: 'ราคาเกษตรกรขายได้ (แป้ง 25%)',
    notes: 'MOC product_id W16031; แสดงช่วง price_min-price_max ของวันที่สำรวจ 2026-05-27',
    price: 3,
    priceMax: 3.55,
    province: 'นครราชสีมา',
    showOnHome: true,
    sourceAttribution: 'ข้อมูลราคาสินค้าเกษตร กรมการค้าภายใน กระทรวงพาณิชย์',
    sourceDisplayName: 'กรมการค้าภายใน กระทรวงพาณิชย์',
    sourceName: 'MOC Open Data / กรมการค้าภายใน',
    sourceType: 'api',
    sourceUrl: 'https://dataapi.moc.go.th/gis-product-prices?product_id=W16031&from_date=2026-05-01&to_date=2026-05-27',
    trend: 'unknown',
    unit: 'บาท/กก.',
    updatedAt: '2026-05-27T00:00:00+07:00',
  },
  {
    category: 'sugarcane',
    commodityCode: 'sugarcane',
    commodityNameTh: 'อ้อย',
    currency: 'THB',
    fetchedAt: '2026-05-27T18:20:00+07:00',
    freshnessPolicy: 'seasonal_reference',
    id: 'prd-thaigov-sugarcane-initial-price-2568-2569',
    marketName: 'ราคาอ้อยขั้นต้น ฤดูการผลิตปี 2568/2569 ระดับความหวาน 10 CCS',
    notes: 'ราคาอ้างอิงตามฤดูการผลิต ไม่ใช่ราคาตลาดรายวัน; ครม.เห็นชอบราคาเดียวทั่วประเทศ',
    price: 890,
    showOnHome: false,
    sourceAttribution: 'กรมประชาสัมพันธ์ / รัฐบาลไทย อ้างข้อมูลมติคณะรัฐมนตรีตามข้อเสนอกระทรวงอุตสาหกรรม',
    sourceDisplayName: 'ข้อมูลอ้างอิงจากรัฐบาลไทย / กรมประชาสัมพันธ์',
    sourceName: 'กรมประชาสัมพันธ์ / รัฐบาลไทย',
    sourceType: 'webpage',
    sourceUrl: 'https://www.prd.go.th/th/content/category/detail/id/33/iid/475030',
    trend: 'unknown',
    unit: 'บาท/ตันอ้อย',
    updatedAt: '2026-02-10T00:00:00+07:00',
  },
];

// Fertilizer is guarded for M119 and remains source-pending until a verified source,
// formula, package size, unit, updatedAt, and fetchedAt are approved.
export const manualFertilizerPriceRows: ManualFertilizerPriceRow[] = [];
