import type { WeatherRiskReviewerHistory } from '@/services/weather/weather-risk-release-audit.types';
import { weatherRiskRuleVersionFixtures } from '@/services/weather/weather-risk-review-fixtures';

const primaryVersion = weatherRiskRuleVersionFixtures[0];

export const weatherRiskReviewerHistoryFixtures: WeatherRiskReviewerHistory[] = [
  {
    id: 'history-reviewer-assigned',
    ruleId: primaryVersion.ruleId,
    versionId: primaryVersion.versionId,
    role: 'agronomy_expert',
    eventType: 'reviewer_assigned',
    toStatus: 'pending',
    actorLabel: 'local fixture',
    changedAt: '2026-05-24T09:00:00.000Z',
    note: 'จำลองการมอบหมายผู้เชี่ยวชาญเกษตร ยังไม่ใช่การอนุมัติจริง',
    staleReviewWarning: false,
    planningOnly: true,
  },
  {
    id: 'history-reviewer-changed',
    ruleId: primaryVersion.ruleId,
    versionId: primaryVersion.versionId,
    role: 'weather_data_reviewer',
    eventType: 'reviewer_changed',
    fromStatus: 'pending',
    toStatus: 'pending',
    actorLabel: 'local fixture',
    changedAt: '2026-05-24T09:10:00.000Z',
    note: 'จำลองการเปลี่ยนผู้ตรวจข้อมูลอากาศ ต้องมี audit ก่อนใช้จริง',
    staleReviewWarning: false,
    planningOnly: true,
  },
  {
    id: 'history-safety-pending',
    ruleId: primaryVersion.ruleId,
    versionId: primaryVersion.versionId,
    role: 'safety_reviewer',
    eventType: 'safety_reviewer_pending',
    toStatus: 'pending',
    actorLabel: 'local fixture',
    changedAt: '2026-05-24T09:20:00.000Z',
    note: 'safety reviewer ยัง pending จึงห้าม prescriptive output',
    staleReviewWarning: false,
    planningOnly: true,
  },
  {
    id: 'history-rule-reverted',
    ruleId: primaryVersion.ruleId,
    versionId: primaryVersion.versionId,
    role: 'agronomy_expert',
    eventType: 'rule_reverted',
    fromStatus: 'review_candidate',
    toStatus: 'planning_only',
    actorLabel: 'local fixture',
    changedAt: '2026-05-24T09:30:00.000Z',
    note: 'จำลองการ revert กฎกลับเป็น planning-only หลังพบข้อความอาจสั่งการเกินไป',
    staleReviewWarning: false,
    planningOnly: true,
  },
  {
    id: 'history-stale-review',
    ruleId: primaryVersion.ruleId,
    versionId: primaryVersion.versionId,
    role: 'weather_data_reviewer',
    eventType: 'stale_review',
    toStatus: 'pending',
    actorLabel: 'local fixture',
    changedAt: '2026-05-24T09:40:00.000Z',
    note: 'review เก่าเกินกว่าจะใช้เป็นการอนุมัติ production',
    staleReviewWarning: true,
    planningOnly: true,
  },
  {
    id: 'history-release-blocked',
    ruleId: primaryVersion.ruleId,
    versionId: primaryVersion.versionId,
    role: 'safety_reviewer',
    eventType: 'release_blocked',
    toStatus: 'blocked',
    actorLabel: 'local fixture',
    changedAt: '2026-05-24T09:50:00.000Z',
    note: 'release ถูก block เพราะยังไม่มี human approval gate',
    staleReviewWarning: false,
    planningOnly: true,
  },
];

export function getWeatherRiskReviewerHistorySummary() {
  return {
    histories: weatherRiskReviewerHistoryFixtures,
    historyCount: weatherRiskReviewerHistoryFixtures.length,
    staleReviewWarnings: weatherRiskReviewerHistoryFixtures.filter((history) => history.staleReviewWarning),
    hasReviewerAssigned: weatherRiskReviewerHistoryFixtures.some((history) => history.eventType === 'reviewer_assigned'),
    hasReviewerChanged: weatherRiskReviewerHistoryFixtures.some((history) => history.eventType === 'reviewer_changed'),
    hasReleaseBlocked: weatherRiskReviewerHistoryFixtures.some((history) => history.eventType === 'release_blocked'),
    planningOnly: weatherRiskReviewerHistoryFixtures.every((history) => history.planningOnly),
  };
}
